resources:
  - name: source-code
    type: git
    source:
      uri: git@github.com:Spidertracks/ops.concourse.git-resource.git
      branch: master
      private_key: ((github_private_rsa_key))

  - name: non-detached-head-git-resource
    type: docker-image
    source:
      repository: ((repository_non-detached-head-git-resource))
      aws_access_key_id: ((aws-access-key-id))
      aws_secret_access_key: ((aws-secret-access-key))

jobs:
- name: Build and Publish Docker Images
  plan:
    - get: source-code
    - task: Ensure Docker Repositories and Parameters up to date
      config: 
        platform: linux
        inputs: 
          - name: source-code
        image_resource: 
          type: docker-image
          source:
            repository: hashicorp/terraform
        params: 
          AWS_ACCESS_KEY_ID: ((aws-access-key-id))
          AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key))
        run: 
          dir: source-code/tf
          path: sh
          args:
            - -xce
            - terraform init &&  terraform apply --auto-approve
    - aggregate:
      - put: non-detached-head-git-resource
        params:
          build: source-code/
          dockerfile: source-code/dockerfiles/alpine/Dockerfile
          tag_file:  source-code/dockerfiles/alpine/tag
    